FROM arm32v7/debian:stretch-slim AS builder

COPY qemu-arm-static /usr/bin

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  echo "deb-src http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y --no-install-recommends install apt-utils git ca-certificates libneon27-gnutls-dev ninja-build && \
  apt-get -y --no-install-recommends build-dep mariadb-server

ARG MARIADB_VERSION=10.3
RUN git clone --branch $MARIADB_VERSION --single-branch --depth=1 https://github.com/MariaDB/server.git /src

WORKDIR /src

#RUN cmake . -DBUILD_CONFIG=mysql_release && make
RUN cmake . \
  -DENABLE_DEBUG_SYNC=OFF \
  -DINSTALL_MYSQLTESTDIR= \
  -DCONC_WITH_{UNITTEST,SSL}=OFF \
  -DWITH_EMBEDDED_SERVER=OFF \
  -DWITH_MARIABACKUP=OFF \
  -DWITH_UNIT_TESTS=OFF \
  -DPLUGIN_ARCHIVE=NO \
  -DPLUGIN_BLACKHOLE=NO \
  -DPLUGIN_CASSANDRA=NO \
  -DPLUGIN_MROONGA=NO \
  -DPLUGIN_OQGRAPH=NO \
  -DPLUGIN_PERFSCHEMA=NO \
  -DPLUGIN_SPHINX=NO \
  -DPLUGIN_SPIDER=NO \
  -DENABLED_PROFILING=OFF \
  -DENABLE_DTRACE=OFF \
  -DENABLE_DEBUG_SYNC=OFF \
  -DWITHOUT_TOKUDB=ON \
  -DWITH_NDB_STORAGE_ENGINE=0 \
  -DWITH_PARTITION_STORAGE_ENGINE=0 \
  -DWITH_OQGRAPH_STORAGE_ENGINE=0 \
  -DWITHOUT_MROONGA_STORAGE_ENGINE=1 \
  -DWITHOUT_ROCKSDB_STORAGE_ENGINE=1 \
  -DWITH_SAFEMALLOC=OFF \
  -DWITH_SSL=bundled \
  -DPLUGIN_EXAMPLE_KEY_MANAGEMENT:STRING="NO" \
  -DPLUGIN_AUDIT_NULL:STRING="NO" \
  -DWITH_NUMA:STRING="NO" \
  -DPLUGIN_QA_AUTH_INTERFACE:STRING="NO" \
  -DPLUGIN_EXAMPLE:STRING="NO" \
  -DPLUGIN_SIMPLE_PASSWORD_CHECK:STRING="DYNAMIC" \
  -DPLUGIN_ARCHIVE:STRING="NO" \
  -DPLUGIN_FEDERATED:STRING="NO" \
  -DPLUGIN_USER_VARIABLES:STRING="STATIC" \
  -DPLUGIN_QUERY_CACHE_INFO:STRING="DYNAMIC" \
  -DPLUGIN_DEBUG_KEY_MANAGEMENT:STRING="NO" \
  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/mysql" \
  -DPLUGIN_TOKUDB:STRING="NO" \
  -DPLUGIN_QA_AUTH_SERVER:STRING="NO" \
  -DPLUGIN_DIALOG_EXAMPLES:STRING="NO" \
  -DPLUGIN_BLACKHOLE:STRING="NO" \
  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" \
  -DPLUGIN_MROONGA:STRING="NO" \
  -DCONNECT_WITH_LIBXML2:BOOL="0" \
  -DPCRE_PARENS_NEST_LIMIT:STRING="250" \
  -DPLUGIN_AUTH_SOCKET:STRING="NO" \
  -DWITH_SYSTEMD:STRING="auto" \
  -DPLUGIN_SPIDER:STRING="NO" \
  -DLIBRARY_OUTPUT_PATH:PATH="" \
  -Dlibmongoc-1.0_DIR:PATH="libmongoc-1.0_DIR-NOTFOUND" \
  -DPLUGIN_PERFSCHEMA:STRING="STATIC" \
  -DPLUGIN_DAEMON_EXAMPLE:STRING="NO" \
  -DPLUGIN_AUTH_0X0100:STRING="NO" \
  -DPLUGIN_FILE_KEY_MANAGEMENT:STRING="DYNAMIC" \
  -DPLUGIN_SERVER_AUDIT:STRING="DYNAMIC" \
  -DCONNECT_WITH_ODBC:BOOL="0" \
  -DWITH_SAFEMALLOC:STRING="AUTO" \
  -DAWS_CPP_SDK_INCLUDE_DIR:PATH="AWS_CPP_SDK_INCLUDE_DIR-NOTFOUND" \
  -DPLUGIN_FTEXAMPLE:STRING="NO" \
  -DWITH_ROCKSDB_snappy:STRING="AUTO" \
  -DWITH_INNODB_LZMA:STRING="AUTO" \
  -DWITH_INNODB_LZ4:STRING="AUTO" \
  -DPLUGIN_TEST_VERSIONING:STRING="DYNAMIC" \
  -DPLUGIN_QA_AUTH_CLIENT:STRING="NO" \
  -DGRN_WITH_KYTEA:STRING="auto" \
  -DGRN_MECAB_CONFIG_ABSOLUTE_PATH:FILEPATH="GRN_MECAB_CONFIG_ABSOLUTE_PATH-NOTFOUND" \
  -DPLUGIN_AUTH_ED25519:STRING="NO" \
  -DPLUGIN_METADATA_LOCK_INFO:STRING="DYNAMIC" \
  -DWITH_EXTRA_CHARSETS:STRING="all" \
  -DPLUGIN_LOCALES:STRING="DYNAMIC" \
  -DWITH_ROCKSDB_zstd:STRING="AUTO" \
  -DCONNECT_WITH_MONGO:BOOL="0" \
  -DPLUGIN_PARTITION:STRING="STATIC" \
  -DJEMALLOC_STATIC_LIBRARY:FILEPATH="JEMALLOC_STATIC_LIBRARY-NOTFOUND" \
  -DCONNECT_WITH_JDBC:BOOL="0" \
  -DPLUGIN_SPHINX:STRING="NO" \
  -DPLUGIN_CLIENT_ED25519:STRING="NO" \
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING="2.4" \
  -DPLUGIN_INNOBASE:STRING="STATIC" \
  -DMRN_DEFAULT_TOKENIZER:STRING="" \
  -DPLUGIN_FEDERATEDX:STRING="NO" \
  -DWITH_INNODB_BZIP2:STRING="AUTO" \
  -DWITH_ROCKSDB_LZ4:STRING="AUTO" \
  -DPLUGIN_AUTH_TEST_PLUGIN:STRING="NO" \
  -DPLUGIN_SEQUENCE:STRING="STATIC" \
  -DBZIP2_DIR:PATH="BZIP2_DIR-NOTFOUND"\
  -DPLUGIN_DISKS:STRING="DYNAMIC"\
  -DCONNECT_WITH_XMAP:BOOL="0"\
  -DWITH_ZLIB:STRING="bundled"\
  -DPLUGIN_TEST_SQL_DISCOVERY:STRING="DYNAMIC"\
  -DPLUGIN_SQL_ERRLOG:STRING="DYNAMIC"\
  -DWITH_INNODB_SNAPPY:STRING="AUTO"\
  -DEXECUTABLE_OUTPUT_PATH:PATH=""\
  -DPLUGIN_QUERY_RESPONSE_TIME:STRING="DYNAMIC"\
  -DWITH_INNODB_LZO:STRING="AUTO"\
  -DINSTALL_LAYOUT:STRING="STANDALONE"\
  -DAWS_CPP_SDK_CORE:FILEPATH="AWS_CPP_SDK_CORE-NOTFOUND"\
  -DWITH_PCRE:STRING="auto"\
  -DMYSQL_MAINTAINER_MODE:STRING="AUTO"\
  -DPLUGIN_CONNECT:STRING="NO"\
  -DCONNECT_WITH_VCT:BOOL="0"\
  -DMUTEXTYPE:STRING="event"\
  -DMYSQL_DATADIR:PATH="/usr/local/mysql/data"\
  -DPLUGIN_FEEDBACK:STRING="STATIC"\
  -DCONC_WITH_UNIT_TESTS:BOOL="0"\
  -DPLUGIN_WSREP_INFO:STRING="DYNAMIC"\
  -DCONNECT_WITH_ZIP:BOOL="0"\
  -DPLUGIN_ROCKSDB:STRING="NO"\
  -DPLUGIN_HANDLERSOCKET:STRING="DYNAMIC"\
  -DWITH_JEMALLOC:STRING="auto"\
  -DENABLED_PROFILING:BOOL="0" \
  -G Ninja

#RUN make -j4
RUN ninja

WORKDIR /src

#RUN make install
RUN ninja install

FROM arm32v7/debian:stretch-slim AS release
ARG DEBIAN_FRONTEND=noninteractive
COPY qemu-arm-static /usr/bin

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends apt-utils && \
  apt-get install -y --no-install-recommends libaio1

WORKDIR /usr/local/mysql

COPY --from=builder /usr/local/mysql /usr/local/mysql

RUN \
  useradd -r mysql && \
  echo <<MYCNF >> /my.cnf \
[mariadb] \
datadir=/var/lib/mysql \
tmpdir=/tmp \
\
lc_messages_dir=/usr/local/mysql/share \
max-connections=20 \
lc-messages=en_us \
innodb_use_native_aio = 0 \
MYCNF && \
  mkdir -p /var/lib/mysql && \
  chown -R mysql /usr/local/mysql/ /var/lib/mysql /my.cnf

VOLUME /var/lib/mysql

COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s /usr/local/bin/docker-entrypoint.sh / # backwards compat
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]
